### PR TITLE
Migrate sample-controller to knative.dev/sample-controller

### PR DESCRIPTION
**Pull request by mattmoor**
/hold

I'd be surprised if this didn't require infrastructure changes :)

### CODE REVIEW

**Comment by adrcunha** [comment]
:cry: 

```
I0619 18:46:29.206] ============================
I0619 18:46:29.213] ==== RUNNING UNIT TESTS ====
I0619 18:46:29.221] ============================
I0619 18:46:29.231] Running tests with 'go test -race -v  ./... '
I0619 18:46:47.626] cmd/controller/main.go:21:2: cannot find package "knative.dev/sample-controller/pkg/reconciler/addressableservice" in any of:
I0619 18:46:47.663] 	/go/src/github.com/knative/sample-controller/vendor/knative.dev/sample-controller/pkg/reconciler/addressableservice (vendor tree)
I0619 18:46:47.674] 	/usr/local/go/src/knative.dev/sample-controller/pkg/reconciler/addressableservice (from $GOROOT)
I0619 18:46:47.683] 	/go/src/knative.dev/sample-controller/pkg/reconciler/addressableservice (from $GOPATH)
```

**Comment by adrcunha** [comment]
Does it work on your machine when you run `./test/presubmit-tests.sh --unit-tests`? (or `--build-tests`)

**Comment by mattmoor** [comment]
@adrcunha yep, talking to @chaodaiG about: https://github.com/kubernetes/test-infra/blob/b3a9e5ba03ff1d38d3dc3a0fae2880874de1db83/config/jobs/kubernetes/sig-gcp/sig-gcp-windows.yaml#L67-L72

**Comment by chaodaiG** [comment]
@adrcunha , I think path_alias would work for us, and there probably is some work around making prow job config generator work smartly with this change. I can look into it

**Comment by mattmoor** [comment]
@adrcunha If I run `go test ./...` it works fine, so long as I am in `$GOPATH/src/knative.dev/sample-controller`

**Comment by chaodaiG** [comment]
It turns out that path_alias doesn't work as is, will need to move from bootstrap to podutil in Prow as in https://github.com/knative/test-infra/issues/265

**Pull request merged**
