### PR TITLE
Update github.com/knative/test-infra dependency

### PR DESCRIPTION
**Pull request by mattmoor-sockpuppet**
Produced via:
  `dep ensure -update github.com/knative/test-infra`
/assign @mattmoor

### CODE REVIEW

**Comment by adrcunha** [comment]
dep is currently unnecessarily pulling test-infra/devstats. This should be addressed soon, so if you're OK with that for a while, unhold; otherwise looks like removing the spurious dir is the only option.

**Comment by adrcunha** [comment]
Related bug in test-infra: https://github.com/knative/test-infra/issues/850

/lgtm
/hold

**Comment by mattmoor** [comment]
@adrcunha I'm not worried about it.  In the grand scheme of things, it's text that compresses well.  I'd be more worried if we were vendoring stuff (without pruning) that checked in large binaries.

/hold cancel

**Pull request merged**
